'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..', '..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const native = fs.readFileSync(path.join(root, 'native/webkit-engine/main.cpp'), 'utf8');
const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
for (const route of ["p === '/downloads'", "p === '/api/files/downloads'", "p.startsWith('/api/files/downloads/')", "Content-Disposition", "application/octet-stream"]) assert.ok(server.includes(route), `missing safe file route: ${route}`);
for (const scheme of ['"http"', '"https"', '"about"', '"data"', '"blob"', '"file"']) assert.ok(native.includes(scheme), `missing native scheme policy: ${scheme}`);
assert.ok(native.includes('webkit_policy_decision_ignore'));
assert.ok(native.includes('g_filename_to_uri'));
assert.ok(html.includes('btn-downloads') && html.includes('/downloads'));
assert.ok(app.includes('if(/^[a-z][a-z0-9+.-]*:/i.test(u))return u;'), 'address bar should preserve explicit schemes for policy validation');
console.log('PASS file/download and protocol policy contract');
