'use strict';
const assert = require('assert');
const path = require('path');
const { pathToFileURL } = require('url');
const { validateNavigation, classifyUrl, classifyResourceType, isWithin } = require('../../lib/navigation-policy');
assert.strictEqual(validateNavigation('https://example.com/'), 'https://example.com/');
assert.strictEqual(validateNavigation('about:blank'), 'about:blank');
assert.strictEqual(classifyUrl('data:text/plain,hello').kind, 'inline-data');
assert.strictEqual(classifyUrl('blob:https://example.com/abc').kind, 'blob-resource');
assert.throws(() => validateNavigation('javascript:alert(1)'), /unsafe/);
assert.throws(() => validateNavigation('vbscript:msgbox(1)'), /unsafe/);
assert.throws(() => validateNavigation('intent://example.com'), /unsafe/);
assert.throws(() => validateNavigation('ftp://example.com/'), /FTP is a legacy/);
assert.throws(() => validateNavigation('mailto:test@example.com'), /External handler/);
assert.throws(() => validateNavigation('tel:+1234567'), /External handler/);
assert.throws(() => validateNavigation('magnet:?xt=urn:btih:abc'), /External handler/);
assert.throws(() => validateNavigation('file:///etc/passwd'), /restricted/);
const profile = process.env.SOLOHOST_BROWSER_DATA || '/app/data/webkit-profile';
assert.strictEqual(classifyUrl(pathToFileURL(path.join(profile, 'downloads', 'sample.txt')).href).kind, 'local-file');
assert.strictEqual(classifyResourceType('https://x.test/file.pdf?download=1'), 'pdf');
assert.strictEqual(classifyResourceType('/music/song.mp3'), 'audio');
assert.strictEqual(classifyResourceType('/data.json'), 'json');
assert.strictEqual(classifyResourceType('/bundle.zip'), 'archive');
assert.strictEqual(isWithin('/safe', '/safe/file.txt'), true);
assert.strictEqual(isWithin('/safe', '/safe-other/file.txt'), false);
console.log('PASS navigation and resource policy');
