'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..', '..');
const monitor = require(path.join(root, 'lib/performance-monitor'));
const sample = monitor.sample({ status: 'ready', tabs: [{ id: 'home' }], active: 'home', processIds: {} });
assert.ok(sample.node && Number.isFinite(sample.node.rssBytes));
assert.ok(sample.cgroupMemory && 'currentBytes' in sample.cgroupMemory);
assert.strictEqual(sample.browser.tabCount, 1);
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const manager = fs.readFileSync(path.join(root, 'lib/chromium-engine.js'), 'utf8');
assert.ok(server.includes("p === '/api/performance'"));
assert.ok(manager.includes('processIds:') && manager.includes('chromiumPid'));
assert.ok(fs.existsSync(path.join(root, 'scripts/benchmark.js')));
console.log('PASS performance telemetry, Chromium process snapshot, benchmark harness');
