'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
console.log('Running SoloHost Browser verification...');
const root = __dirname;
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
assert.ok(pkg.dependencies.express);
assert.ok(!pkg.dependencies.playwright);
assert.ok(fs.existsSync(path.join(root, 'lib/ai-module/ai-service.js')));
assert.ok(fs.existsSync(path.join(root, 'lib/feedback-module/feedback-service.js')));
assert.ok(fs.existsSync(path.join(root, 'public/ai-panel.js')));
assert.ok(fs.existsSync(path.join(root, 'public/ai-module/ai-module.js')));
assert.ok(fs.existsSync(path.join(root, 'lib/app-adapter.js')));
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
assert.ok(server.includes('mountAIRoutes'));
assert.ok(server.includes('mountFeedbackRoutes'));
assert.ok(server.includes('/api/proxy'));
assert.ok(server.includes('/api/browser/history'));
assert.ok(server.includes('/api/browser/bookmarks'));
assert.ok(!server.includes("require('./browser-gateway')"));
const fb = fs.readFileSync(path.join(root, 'lib/feedback-module/feedback-service.js'), 'utf8');
assert.ok(fb.includes('SHFH-CANNOI-0905428801'));
const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
assert.ok(html.includes('id="aiFab"'));
assert.ok(html.includes('ai-module/ai-module.js'));
assert.ok(html.includes('feedback-module/feedback-module.js'));
assert.ok(html.includes('setProvider'));
assert.ok(html.includes('tab-strip'));
assert.ok(html.includes('library-overlay'));
const appJs = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
assert.ok(appJs.includes('function newTab'));
assert.ok(appJs.includes('function addCurrentBookmark'));
assert.ok(appJs.includes('saveVisit(url)'));
console.log('✓ package.json');
console.log('✓ required files');
console.log('✓ contracts');

// WebView proxy rendering/security regression tests.
const proxy = require('./lib/frame-proxy');
assert.strictEqual(proxy.isPrivateIp('127.0.0.1'), true);
assert.strictEqual(proxy.isPrivateIp('10.1.2.3'), true);
assert.strictEqual(proxy.isPrivateIp('192.168.1.1'), true);
assert.strictEqual(proxy.isPrivateIp('169.254.169.254'), true);
assert.strictEqual(proxy.isPrivateIp('224.0.0.1'), true);
assert.strictEqual(proxy.isPrivateIp('::1'), true);
assert.strictEqual(proxy.isPrivateIp('::ffff:127.0.0.1'), true);
assert.strictEqual(proxy.isPrivateIp('8.8.8.8'), false);

const rewritten = proxy.rewriteHtml('<html><head><link rel="stylesheet" href="/site.css"></head><body><img src="/hero.png"><script src="/app.js"></script><a href="https://example.com/path">Next</a></body></html>', 'https://example.org/page');
// Navigation links stay on proxy; static assets use absolute origin URLs (avoids nested proxy + log flood).
assert.ok(rewritten.includes('/api/proxy?url='), 'anchors should be routed through the proxy');
assert.ok(rewritten.includes('https://example.org/site.css'), 'stylesheets should be absolute origin, not nested proxy');
assert.ok(rewritten.includes('https://example.org/hero.png'), 'images should be absolute origin');
assert.ok(rewritten.includes('name="viewport"'), 'mobile viewport should be present');
assert.ok(!rewritten.includes('href="https://example.com/path"'), 'external anchors should be routed through the proxy');
const css = proxy.rewriteCss('.hero{background:url("../img/a.png")} @import "./theme.css";', 'https://example.org/css/site.css');
assert.ok(css.includes('https://example.org/img/a.png'), 'CSS url() should absolutize to origin');
assert.ok(css.includes('https://example.org/css/theme.css'), 'CSS @import should absolutize to origin');
assert.ok(!css.includes('/api/proxy?url='), 'CSS must not nest proxy URLs');
// Nested proxy unwrap
assert.ok(proxy.normalizeTargetUrl('http://14.176.78.46:62160/api/proxy?url=' + encodeURIComponent('https://static.example.com/a.css')) === 'https://static.example.com/a.css');
(async () => {
  await assert.rejects(proxy.assertPublicHttpUrl('file:///etc/passwd'));
  await assert.rejects(proxy.assertPublicHttpUrl('http://127.0.0.1/'));
  await assert.rejects(proxy.assertPublicHttpUrl('http://[::1]/'));
  await assert.rejects(proxy.assertPublicHttpUrl('http://user:pass@example.com/'));
  console.log('✓ proxy rendering and SSRF regression checks');
  console.log('All static tests passed successfully.');
})().catch(err => { console.error(err); process.exitCode = 1; });
