'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
console.log('Running SoloHost Browser verification...');
const root = __dirname;
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
assert.ok(pkg.dependencies.express);
assert.ok(!pkg.dependencies.playwright);
assert.ok(fs.existsSync(path.join(root, 'lib/ai-module/ai-service.js')));
assert.ok(fs.existsSync(path.join(root, 'lib/feedback-module/feedback-service.js')));
assert.ok(fs.existsSync(path.join(root, 'public/ai-panel.js')));
assert.ok(fs.existsSync(path.join(root, 'public/ai-module/ai-module.js')));
assert.ok(fs.existsSync(path.join(root, 'lib/app-adapter.js')));
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
assert.ok(server.includes('mountAIRoutes'));
assert.ok(server.includes('mountFeedbackRoutes'));
assert.ok(server.includes('/api/proxy'));
assert.ok(!server.includes("require('./browser-gateway')"));
const fb = fs.readFileSync(path.join(root, 'lib/feedback-module/feedback-service.js'), 'utf8');
assert.ok(fb.includes('SHFH-CANNOI-0905428801'));
const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
assert.ok(html.includes('id="aiFab"'));
assert.ok(html.includes('ai-module/ai-module.js'));
assert.ok(html.includes('feedback-module/feedback-module.js'));
assert.ok(html.includes('setProvider'));
console.log('✓ package.json');
console.log('✓ required files');
console.log('✓ contracts');
console.log('All static tests passed successfully.');
