'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');

console.log('Running SoloHost Browser v9 verification...');
const root = __dirname;
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
assert.ok(pkg.dependencies.express);
assert.ok(!pkg.dependencies.playwright, 'playwright must be removed');
assert.ok(!pkg.dependencies['playwright-core'], 'playwright-core must be removed');
assert.ok(fs.existsSync(path.join(root, 'public/reader-injector.js')));
assert.ok(fs.existsSync(path.join(root, 'public/app.js')));
assert.ok(fs.existsSync(path.join(root, 'public/index.html')));
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
assert.ok(server.includes('/api/ai/process'));
assert.ok(server.includes('0.0.0.0') || server.includes("HOST"));
assert.ok(server.includes('client-webview') || server.includes('client WebView'));
assert.ok(!server.includes("require('./browser-gateway')"));
const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
assert.ok(html.includes('main-webview'));
assert.ok(html.includes('reader-injector.js'));
const docker = fs.readFileSync(path.join(root, 'Dockerfile'), 'utf8');
assert.ok(/alpine/i.test(docker));
assert.ok(!/playwright/i.test(docker));
console.log('✓ package.json');
console.log('✓ required files');
console.log('✓ contracts');
console.log('All static tests passed successfully.');
